services:
    sonata.admin.listing:
        class: Kisaan\CoreBundle\Admin\ListingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Listings", label: "Listings" }
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\Listing
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]
            - [ setIncludeVat, ["%kisaan.include_vat%"]]
            - [ setBundlesEnabled, ["%kernel.bundles%"]]

    sonata.admin.booking:
        class: Kisaan\CoreBundle\Admin\BookingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bookings", label: "Bookings" }
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\Booking
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]
            - [ setTimeUnit, ["%kisaan.time_unit%"]]
            - [ setBookingExpirationDelay, ["%kisaan.booking.expiration_delay%"]]
            - [ setBookingAcceptationDelay, ["%kisaan.booking.acceptation_delay%"]]
            - [ setIncludeVat, ["%kisaan.include_vat%"]]
            - [ setBundlesEnabled, ["%kernel.bundles%"]]
            - [ setTimezone, ["%kisaan.time_zone%"]]

    sonata.admin.listing_characteristic:
        class: Kisaan\CoreBundle\Admin\ListingCharacteristicAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Listings",  label: "Characteristic" }
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\ListingCharacteristic
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]

    sonata.admin.listing_characteristic_group:
        class: Kisaan\CoreBundle\Admin\ListingCharacteristicGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Listings",  label: "Characteristic Group"}
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\ListingCharacteristicGroup
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]

    sonata.admin.listing_characteristic_type:
        class: Kisaan\CoreBundle\Admin\ListingCharacteristicTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Listings",  label: "Characteristic Type" }
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\ListingCharacteristicType
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]

    sonata.admin.listing_characteristic_value:
        class: Kisaan\CoreBundle\Admin\ListingCharacteristicValueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\ListingCharacteristicValue
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]

    sonata.admin.listing_category:
        class: Kisaan\CoreBundle\Admin\ListingCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Listings",  label: "Category" }
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\ListingCategory
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]
            - [ setBundlesEnabled, ["%kernel.bundles%"]]

    sonata.admin.booking_bank_wire:
        class: Kisaan\CoreBundle\Admin\BookingBankWireAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bookings", label: "Bank Wires"}
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\BookingBankWire
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]
            - [ setTimeUnit, ["%kisaan.time_unit%"]]
            - [ setCurrency, ["%kisaan.currency%"]]
            - [ setBookingBankWireManager, ["@kisaan.booking_bank_wire.manager"]]
            - [ setBundlesEnabled, ["%kernel.bundles%"]]
            - [ setTimezone, ["%kisaan.time_zone%"]]

    sonata.admin.booking_payin_refund:
        class: Kisaan\CoreBundle\Admin\BookingPayinRefundAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bookings", label: "Payin Refunds" }
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\BookingPayinRefund
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]
            - [ setTimeUnit, ["%kisaan.time_unit%"]]
            - [ setBundlesEnabled, ["%kernel.bundles%"]]
            - [ setTimezone, ["%kisaan.time_zone%"]]

    sonata.admin.booking_user_address:
        class: Kisaan\CoreBundle\Admin\BookingUserAddressAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - Kisaan\CoreBundle\Entity\BookingUserAddress
            - ~
        calls:
            - [ setTranslationDomain, [kisaan_user]]
            - [ setLocales, ["%kisaan.locales%"]]