parameters:
    kisaan.listing_activated_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:listing_activated_offerer.txt.twig"
    kisaan.booking_request_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:booking_request_offerer.txt.twig"
    kisaan.booking_request_asker.email.template: "KisaanCoreBundle:Mails/Asker:booking_request_asker.txt.twig"
    kisaan.booking_accepted_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:booking_accepted_offerer.txt.twig"
    kisaan.booking_accepted_asker.email.template: "KisaanCoreBundle:Mails/Asker:booking_accepted_asker.txt.twig"
    kisaan.booking_refused_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:booking_refused_offerer.txt.twig"
    kisaan.booking_refused_asker.email.template: "KisaanCoreBundle:Mails/Asker:booking_refused_asker.txt.twig"
    kisaan.booking_request_expired_asker.email.template: "KisaanCoreBundle:Mails/Asker:booking_request_expired_asker.txt.twig"
    kisaan.booking_request_expired_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:booking_request_expired_offerer.txt.twig"
    kisaan.booking_canceled_by_asker_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:booking_canceled_by_asker_offerer.txt.twig"
    kisaan.booking_canceled_by_asker_asker.email.template: "KisaanCoreBundle:Mails/Asker:booking_canceled_by_asker_asker.txt.twig"
    kisaan.booking_imminent_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:booking_imminent_offerer.txt.twig"
    kisaan.booking_imminent_asker.email.template: "KisaanCoreBundle:Mails/Asker:booking_imminent_asker.txt.twig"
    kisaan.booking_request_expiration_alert_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:booking_request_expiration_alert_offerer.txt.twig"
    kisaan.reminder_to_rate_asker_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:reminder_to_rate_asker_offerer.txt.twig"
    kisaan.booking_bank_wire_transfer_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:booking_bank_wire_transfer_offerer.txt.twig"
    kisaan.update_your_calendar_offerer.email.template: "KisaanCoreBundle:Mails/Offerer:update_your_calendar_offerer.txt.twig"
    kisaan.payment_error_asker.email.template: "KisaanCoreBundle:Mails/Asker:payment_error_asker.txt.twig"
    kisaan.reminder_to_rate_offerer_asker.email.template: "KisaanCoreBundle:Mails/Asker:reminder_to_rate_offerer_asker.txt.twig"
    kisaan.admin_message.email.template: "KisaanCoreBundle:Mails:admin_message.txt.twig"

services:
    kisaan.mailer.twig_swift:
        class: Kisaan\CoreBundle\Mailer\TwigSwiftMailer
        arguments:
            - "@mailer"
            - "@router"
            - "@twig"
            - "@request_stack"
            - "@translator.default"
            - parameters:
                kisaan_time_unit: "%kisaan.time_unit%"
                kisaan_locales: "%kisaan.locales%"
                kisaan_locale: "%kisaan.locale%"
                kisaan_time_zone: "%kisaan.time_zone%"
                kisaan_from_email: "%kisaan.from_email%"
                kisaan_contact_email: "%kisaan.contact_mail%"
            - templates:
                listing_activated_offerer: "%kisaan.listing_activated_offerer.email.template%"
                booking_request_offerer: "%kisaan.booking_request_offerer.email.template%"
                booking_accepted_offerer: "%kisaan.booking_accepted_offerer.email.template%"
                booking_canceled_by_asker_offerer: "%kisaan.booking_canceled_by_asker_offerer.email.template%"
                booking_canceled_by_asker_asker: "%kisaan.booking_canceled_by_asker_asker.email.template%"
                booking_request_expired_offerer: "%kisaan.booking_request_expired_offerer.email.template%"
                booking_request_expired_asker: "%kisaan.booking_request_expired_asker.email.template%"
                booking_request_asker: "%kisaan.booking_request_asker.email.template%"
                booking_accepted_asker: "%kisaan.booking_accepted_asker.email.template%"
                booking_refused_asker: "%kisaan.booking_refused_asker.email.template%"
                booking_refused_offerer: "%kisaan.booking_refused_offerer.email.template%"
                booking_imminent_offerer: "%kisaan.booking_imminent_offerer.email.template%"
                booking_imminent_asker: "%kisaan.booking_imminent_asker.email.template%"
                booking_request_expiration_alert_offerer: "%kisaan.booking_request_expiration_alert_offerer.email.template%"
                booking_bank_wire_transfer_offerer: "%kisaan.booking_bank_wire_transfer_offerer.email.template%"
                reminder_to_rate_asker_offerer: "%kisaan.reminder_to_rate_asker_offerer.email.template%"
                reminder_to_rate_offerer_asker: "%kisaan.reminder_to_rate_offerer_asker.email.template%"
                update_your_calendar_offerer: "%kisaan.update_your_calendar_offerer.email.template%"
                payment_error_asker: "%kisaan.payment_error_asker.email.template%"
                admin_message: "%kisaan.admin_message.email.template%"
