services:
    #Param converters
    kisaan.listing_param_converter:
        class: Kisaan\CoreBundle\Request\ListingParamConverter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
        tags:
            - { name: request.param_converter, priority: 0, converter: listing }

    kisaan.listing_availability_param_converter:
        class: Kisaan\CoreBundle\Request\ListingAvailabilityParamConverter
        arguments:
            - "@doctrine.odm.mongodb.document_manager"
        tags:
            - { name: request.param_converter, priority: -1, converter: listing_availability }
