services:
    #Listeners
    kisaan_user.user_request.listener:
        class: Kisaan\UserBundle\Listener\UserRequestListener
        arguments:
            - "@security.token_storage"
            - "%kisaan.time_zone%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }

    kisaan_user.user_entity_listener:
        class: Kisaan\UserBundle\Listener\UserEntityListener
        arguments:
            - "@event_dispatcher"
            - "@session"
            - "%kisaan.time_zone%"
        tags:
            - { name: doctrine.event_subscriber }

    kisaan_user.user_image_upload_listener:
        class: Kisaan\UserBundle\Listener\UserImageUploadListener
        arguments:
            - "@kisaan_user.user_manager"
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: "onUpload" }

    kisaan_user.listing_image_upload_validation_listener:
        class: Kisaan\UserBundle\Listener\UserImageUploadValidationListener
        arguments:
            - "%kisaan.user_img_max_upload_size%"
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.validation, method: "onValidate" }