services:
    #Voters
    security.access.user_image_voter:
        class:      Kisaan\UserBundle\Security\Voter\UserImageVoter
        public:     false
        tags:
           - { name: security.voter }

    kisaan_user.security.access.user_image_voter:
        class:      Kisaan\UserBundle\Security\Voter\UserImageVoter
        public:     false
        tags:
           - { name: security.voter }