services:
    sonata.admin.footer:
        class: Kisaan\CMSBundle\Admin\FooterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site", label: "Footers" }
        arguments:
            - ~
            - Kisaan\CMSBundle\Entity\Footer
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]
            - [ setFooterManager, ["@kisaan_cms.footer.manager"]]
