services:
    sonata.admin.thread:
        class: Kisaan\MessageBundle\Admin\ThreadAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Messages" }
        arguments:
            - ~
            - Kisaan\MessageBundle\Entity\Thread
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]

    sonata.admin.message:
        class: Kisaan\MessageBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - Kisaan\MessageBundle\Entity\Message
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%kisaan.locales%"]]